<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <TargetName>Soundboword</TargetName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CliWrap" />

        <PackageReference Include="Tmds.DBus.Generator" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Soundboword\Soundboword.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="DBusXml/*.xml" Namespace="Soundboword.Generated" DBusGeneratorMode="Proxy" />
        <EmbeddedResource Include="PipeWire/Wizard/Soundboword.conf" />
    </ItemGroup>

</Project>
