<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" />

        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />

        <PackageReference Include="SoundFlow" />
        <PackageReference Include="SoundFlow.Midi.PortMidi" />

        <PackageReference Include="YoutubeExplode.Converter" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="OutputDevices\DevicesView.axaml.cs">
            <DependentUpon>DevicesView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Sounds\EditSoundView.axaml.cs">
            <DependentUpon>EditSoundView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Sounds\SoundView.axaml.cs">
            <DependentUpon>SoundView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Playbacks\SoundPlaybackView.axaml.cs">
            <DependentUpon>SoundPlaybackView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Playbacks\PlaybacksView.axaml.cs">
            <DependentUpon>PlaybacksView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Sounds\BoardView.axaml.cs">
            <DependentUpon>BoardView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Inputs\InputsView.axaml.cs">
            <DependentUpon>InputsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

</Project>
