<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <TargetName>Soundboword</TargetName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Soundboword\Soundboword.csproj" />
    </ItemGroup>

</Project>
