name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  
  build:
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            project: Linux
          - os: windows-latest
            project: Windows
        
    runs-on: ${{ matrix.os }}
    
    steps:
      
      - name: Build
        working-directory: Soundboword.${{ matrix.project }}
        run: dotnet publish -o OUT
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: OUT/
          name: ${{ matrix.project }}