name: Release

on:
  release: 
    types: [ published ]

permissions: 
  contents: write

jobs:
  
  upload:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/download-artifact@v8.0.1
        with: 
          skip-decompress: true
          name: 